DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL,
    LS_MOD_TS TIMESTAMP
);

CREATE INDEX idx_products_price ON PRODUCT(price);

CREATE INDEX idx_products_LS_MOD_TS ON PRODUCT(LS_MOD_TS);